# Generated by Django 4.1.5 on 2023-01-15 18:00

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SearchRequest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('client', models.IntegerField()),
                ('keywords', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), size=None)),
                ('is_active', models.BooleanField(default=True)),
                ('last_checked', models.IntegerField(default=0)),
                ('channels', models.ManyToManyField(related_name='channels', to='telegram_api.channel')),
                ('groups', models.ManyToManyField(related_name='groups', to='telegram_api.channel')),
            ],
        ),
    ]
