# Generated by Django 4.1.5 on 2023-01-15 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchrequest',
            name='channels',
            field=models.ManyToManyField(blank=True, related_name='channels', to='telegram_api.channel'),
        ),
        migrations.AlterField(
            model_name='searchrequest',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='groups', to='telegram_api.channel'),
        ),
    ]
