# Generated by Django 4.1.5 on 2023-01-15 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_api', '0002_alter_searchrequest_channels_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
