# Generated by Django 4.1.5 on 2023-01-16 01:00

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_api', '0004_remove_searchrequest_last_checked_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchrequest',
            name='added_messages',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=[], size=None),
        ),
    ]
