# Generated by Django 4.1.5 on 2023-01-16 01:00

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_api', '0005_alter_searchrequest_added_messages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchrequest',
            name='added_messages',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, size=None),
        ),
    ]
