# Generated by Django 4.1.5 on 2023-01-17 13:15

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_api', '0006_alter_searchrequest_added_messages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='searchrequest',
            name='channels',
        ),
        migrations.AddField(
            model_name='searchrequest',
            name='channels',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), default=[], size=None),
            preserve_default=False,
        ),
    ]
